version: '3.3'
services:
  proxy:
    build: ./nginx/
    hostname: ${TBCLIENT:-dafne-it}
    ports:
      - 80:80
    container_name: proxy
    depends_on:
      - app
    links:
      - node
    volumes:
      - crm
  app:
    image: node:carbon
    container_name: app
    volumes:
      - /mnt/hgfs/A/experiments/fromwin/:/home/node/app
      - crm:/home/node/app

  node:
    build: ./node/
    hostname: ${TBCLIENT:-dafne-it}.node
    container_name: node
    depends_on:
      - app
    environment:
      - TBCLIENT=${TBCLIENT:-dafne-it}
    volumes:
      - crm
    expose:
      - 8008
volumes:
  crm: